### PR TITLE
Adding PMC ID to property store

### PR DESCRIPTION
**Pull request by Daniel-Mietchen**
i.e. https://www.wikidata.org/wiki/Property:P932

### CODE REVIEW

**Comment by stuppie** [comment]
Should this not be a core ID? It should be unique within Wikidata, right? @sebotic

**Comment by sebotic** [comment]
yeah, that could be added to the core ID list. But you can specify your custom list of core ids when instantiating WDItemEngine anyway. As we do not know which of the 4000 properties should actually unique.

**Comment by stuppie** [comment]
@Daniel-Mietchen Can you change this to be a core id?

**Comment by Daniel-Mietchen** [comment]
Done.

**Comment by stuppie** [comment]
There is a syntax error, missing a comma line 483. Please fix

**Pull request closed without merging**
